# Generated by Django 2.0.6 on 2018-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='arpa_tohumu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='elma_tohumu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='karakter_durum',
            field=models.CharField(default='Boş Bekliyor', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='karakter_gorunus',
            field=models.CharField(default='x', max_length=3),
        ),
    ]
