# Generated by Django 2.0.6 on 2018-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180628_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='arpa_tohumu_sure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='elma_tohumu_sure',
            field=models.IntegerField(default=0),
        ),
    ]
